language: rust

rust:
    - stable
    - nightly

notifications:
    irc: "irc.mozilla.org#piston-internals"

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo test --features="serde_serialization" --no-default-features --verbose
    - cargo doc --verbose

